




columns = [
    "fiscalDateEnding",
    "totalAssets",
    "totalCurrentAssets",
    "cashAndCashEquivalentsAtCarryingValue",
    "cashAndShortTermInvestments",
    "inventory",
    "currentNetReceivables",
    "totalNonCurrentAssets",
    "propertyPlantEquipment",
    "accumulatedDepreciationAmortizationPPE",
    "intangibleAssets",
    "intangibleAssetsExcludingGoodwill",
    "goodwill",
    "investments",
    "longTermInvestments",
    "shortTermInvestments",
    "otherCurrentAssets",
    "otherNonCurrentAssets",
    "totalLiabilities",
    "totalCurrentLiabilities",
    "currentAccountsPayable",
    "deferredRevenue",
    "currentDebt",
    "shortTermDebt",
    "totalNonCurrentLiabilities",
    "capitalLeaseObligations",
    "longTermDebt",
    "currentLongTermDebt",
    "longTermDebtNoncurrent",
    "shortLongTermDebtTotal",
    "otherCurrentLiabilities",
    "otherNonCurrentLiabilities",
    "totalShareholderEquity",
    "treasuryStock",
    "retainedEarnings",
    "commonStock",
    "commonStockSharesOutstanding",
    "currentRatio",
    "quickRatio",
    "cashRatio",
    "debtToAssetsRatio",
    "debtToEquityRatio",
    "equityRatio",
    "workingCapital",
    "netWorkingCapitalRatio",
    "bookValuePerShare"]
